### PR TITLE
Make the default geometry columns in `GeoParquet.write` be `GI.geometrycolumns`

### PR DESCRIPTION
**Pull request by asinghvi17**
Does what it says on the tin

### CODE REVIEW

**Comment by rafaqz** [comment]
While we're at it should we standardise the keyword? Community interface style?

`geometrycolums` would make it pretty clear it's the same thing as `GI.geometrycolumns`

**Comment by asinghvi17** [comment]
Yeah more standardized kwargs would be good.  That will need a bigger rewrite so I'll do that when not bouncing around :D.

**Comment by rafaqz** [comment]
I think this needs a breaking bump anyway (as e.g. the output of GADM.jl won't write after this, it has a broken column name)

So we may as well do both

**Comment by asinghvi17** [comment]
Yes this will be a problem.  GADM should ideally return something usable too...

**Comment by rafaqz** [comment]
See https://github.com/JuliaGeo/GADM.jl/issues/50 for GADM

**Pull request merged**
